# An easy way to run tests locally without Nodejs installed:
#
#     docker build -t sqliteviz/test -f Dockerfile.test .
#

FROM node:18.20.8-bookworm

RUN set -ex; \
    apt update; \
    apt install -y chromium firefox-esr; \
    npm install -g npm@10

WORKDIR /tmp/build

COPY package.json package-lock.json ./
COPY lib lib
RUN npm install

COPY . .

RUN set -ex; \
    sed -i 's/browsers: \[.*\],/browsers: ['"'FirefoxHeadlessTouch'"'],/' karma.conf.cjs

RUN npm run lint -- --no-fix && npm run test
